In [ ]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('../Data/Train.txt', unpack=True, dtype='float32')
x_data = xy[0:-1]
y_data = xy[-1]

print(x_data)
print(y_data)

[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.]
 [ 1.  2.  4.  5.  5.  5.]]
[ 0.  0.  0.  1.  1.  1.]


In [1]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1,len(x_data)], -1.0, 1.0))

# Our hypothesis
h = tf.matmul(W,X)
hypothesis = tf.div(1., 1.+tf.exp(-h))

NameError: name 'tf' is not defined

In [3]:
# Cost function
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

# Minimize
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

In [4]:
# Before starting, initialize the variables.
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [6]:
for step in range(2001):
    sess.run(train, feed_dict={X:x_data, Y:y_data})
    if step % 100 == 0:
        print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

0 0.182251 [[-7.66623306  0.22850253  1.71502864]]
100 0.178872 [[-7.84612513  0.23075722  1.75268054]]
200 0.175668 [[-8.02130413  0.23275055  1.78948927]]
300 0.172619 [[-8.19215202  0.23451449  1.8255167 ]]
400 0.16971 [[-8.35900497  0.23607732  1.860816  ]]
500 0.166929 [[-8.52216053  0.23746321  1.89543557]]
600 0.164262 [[-8.68187332  0.23869225  1.92941713]]
700 0.161702 [[-8.83837605  0.23978294  1.9627986 ]]
800 0.159238 [[-8.99187374  0.24075094  1.99561357]]
900 0.156864 [[-9.14254284  0.24160932  2.02789187]]
1000 0.154572 [[-9.29054546  0.24236952  2.05966067]]
1100 0.152358 [[-9.43602753  0.24304247  2.09094477]]
1200 0.150216 [[-9.57912254  0.24363776  2.12176561]]
1300 0.14814 [[-9.71995068  0.2441629   2.15214515]]
1400 0.146128 [[-9.85861778  0.24462526  2.18210077]]
1500 0.144174 [[-9.99522209  0.24503058  2.21164989]]
1600 0.142277 [[-10.12985611   0.24538581   2.24080801]]
1700 0.140432 [[-10.26259708   0.2456945    2.26958966]]
1800 0.138637 [[-10.39352417   0.245

In [7]:
print(sess.run(hypothesis, feed_dict={X:[[1], [2], [2]]}) > 0.5)

[[False]]


In [8]:
print(sess.run(hypothesis, feed_dict={X:[[1,1], [4,3], [3,5]]}) > 0.5)

[[False  True]]
